# configs/env.yaml
# Environment parameters configuration (randomly generated obstacles, forbidden in pursuer generation area)
observation_seq_len: 8    # observation sequence length N
p_drop: 0.2                # probability of target state information loss
env_size: [150, 150]       # environment size [width, height]

# Obstacles: randomly generated (excluding pursuer generation area)
num_obstacles: 10
obstacle_min_radius: 1.0
obstacle_max_radius: 2.0
auto_generate_obstacles: True   # automatically generate obstacles if obstacles is empty in reset()
regen_obstacles_per_episode: True   # re-generate obstacles for each episode
# If you switch the stage using env.set_num_obstacles(n), you can set auto_generate_obstacles to False to disable automatic generation.
# forbidden / pursuer generation area (absolute coordinates), format [x0, y0, x1, y1]
pursuer_spawn_box: [74.0, 74.0, 76.0, 76.0]

# Kinematics / Dynamics
max_speed: 3.0
max_angular_speed: 3.14
max_linear_accel: 1.5
max_angular_accel: 1.5708
dt: 0.1
target_speed: 1.0

# reproducibility
seed: 36
test_mode: False   # set to True to use RNG with given seed for reproducibility

# obs / act dims
obs_dim: 20
act_dim: 2

# debug / safety
min_agent_spawn_separation_frac: 0.12  # minimum separation fraction with diagonal length (for spawn)
